### ISSUE TITLE
Support for WS2812 or similar Leds with Data pin?

### ISSUE THREAD

**Issue by MischaI** [DutchDevelop/BLLEDController#4]

**Comment by Elektroarzt** [comment]
I would appreciate this too. Not only wiring would be reduced, also there would be way more possibilities in optical differentiating between error states and so on.

**Comment by madnotna** [comment]
I came across a blled competitor, the Lumin. This one looks very promising with support for WS2812b LEDs. The PCB is slightly more expensive but has more options.

**Comment by AGlElectronics** [comment]
Hello I'm the designer of lumin. (Alan) 

It as of now doesn't yet support ws2812b adressable leds however during the beta fase of the project I will be adding support, witch is currently going on (only shipped out the boards last week so still early) if your interested in joining the beta testers I have a very limited amount of slots left (2 as of typing) send me a email or join the discord. 
Bolth can be found on my website: https://www.aglelectronics.com
Note this website is is currently being reworked by my developer and thr downloads section isn't working however the contact me form should be. 

Also this msg is probably going to get deleted cus Dutch doesn't rly like me anymore.

**Comment by DutchDevelop** [comment]
this github repo isnt the place for advertising a product. please refrain from doing it again.
@madnotna the blled is capable of doing ws2812b, there is firmware fork which you can use

**Comment by MischaI** [comment]
@DutchDevelop can u please provide link to this fork, Name of fork developer?
Regards
