### ISSUE TITLE
dimming option please

### ISSUE THREAD

**Issue by chuckkay** [DutchDevelop/BLLEDController#6]
i see no way to dim the lights, unless i install a dimmer dial..

the multicolr led strip i purchaced is dimmable, but BL-LED  is the only controler installed.. with no instructions provided to send it commands

**Comment by chuckkay** [comment]
well i was looking for the ability to dim the light, or fingers crossed
control it with alexa or some other home automation, but if you just need
to stick with MQTT i think an option to access in the settings, to do the
following as you currently have it that when a print finishes you change
the lights to green and a few minutes later they go back to white. that
must be some timing settings you put in arbitrarily, perhaps through the
app let us have control over how much time to wait before going to white as
long as the printer is idle, and then give us the option to set lights to
go off x minutes after a completed job so long as a new job is not running.

thanks

**Comment by DutchDevelop** [comment]
This option has been added in the newest expirimental version
