### ISSUE TITLE
Can't upload New firmware with update menu

### ISSUE THREAD

**Issue by Legired** [DutchDevelop/BLLEDController#9]
Hello,

I want to use the experimental firmware, with the dimmable option for the LED, because i think mine are too bright, but i get an error when i try to change the firmware with the "upload" menu and upload the .bin file, here the error : 

![IMG_20231103_212709](https://github.com/DutchDevelop/BLLEDController/assets/33747013/1796d5e1-890b-4a19-9c44-51e6d5d17b69)

I download the .bin here :  https://github.com/DutchDevelop/BLLEDController/blob/main/firmware/esp32dev/BLLC_Expirimental_20.10.23.bin

I check the board, and i have the es32 board
![IMG_20231104_074528](https://github.com/DutchDevelop/BLLEDController/assets/33747013/6f95de18-e65e-4312-9a15-42c11b380039)

i also try with every Expirimental and the v.07 version but everytime i got this error 

Thx in advance

**Comment by MrTom1** [comment]
I have same problem with my device. Any idea?

**Comment by Waschmabiene** [comment]
Read his Guide to install and config experimental Firmware here:
[https://dutchdevelop.com/the-new-blledcontroller-guide-revised/](https://dutchdevelop.com/the-new-blledcontroller-guide-revised/)
